/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-4-12: 23h:22m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2
//
#include _ATS_CCOMP_PRELUDE_USER2
//
#endif /* _ATS_CCOMP_PRELUDE_USER2 */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__fact, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_mac(atspre_assert_errmsg_bool0)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__fact(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
mainats_void_int() ;
#endif // end of [QUALIFIED]

/*
/home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 52(line=6, offs=16) -- 95(line=6, offs=59)
*/
/*
local: 
global: fact$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__fact(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 47(line=6, offs=11) -- 95(line=6, offs=59)
*/
ATSINSflab(__patsflab_fact):
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 61(line=6, offs=25) -- 66(line=6, offs=30)
*/
ATSINSmove(tmp1, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 58(line=6, offs=22) -- 95(line=6, offs=59)
*/
ATSif(
tmp1
) ATSthen() {
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 72(line=6, offs=36) -- 73(line=6, offs=37)
*/
ATSINSmove(tmpret0, ATSPMVi0nt(1)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 89(line=6, offs=53) -- 94(line=6, offs=58)
*/
ATSINSmove(tmp3, PMVtmpltcstmat[0](g0int_sub<S2Eextkind(atstype_int)>)(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 83(line=6, offs=47) -- 95(line=6, offs=59)
*/
ATSINSmove(tmp2, _057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__fact(tmp3)) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 79(line=6, offs=43) -- 95(line=6, offs=59)
*/
ATSINSmove(tmpret0, PMVtmpltcstmat[0](g0int_mul<S2Eextkind(atstype_int)>)(arg0, tmp2)) ;

} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__fact] */

/*
/home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 112(line=9, offs=6) -- 216(line=13, offs=2)
*/
/*
local: 
global: mainats_void_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
mainats_void_int()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp5, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp6) ;
// ATStmpdec_void(tmp7) ;
// ATStmpdec_void(tmp8) ;
// ATStmpdec_void(tmp9) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 107(line=9, offs=1) -- 216(line=13, offs=2)
*/
ATSINSflab(__patsflab_main_void_int):
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 117(line=9, offs=11) -- 216(line=13, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 139(line=10, offs=13) -- 147(line=10, offs=21)
*/
ATSINSmove(tmp5, _057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__fact(ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 159(line=11, offs=12) -- 183(line=11, offs=36)
*/
ATSINSmove_void(tmp6, atspre_print_string(ATSPMVstring("ans = "))) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 159(line=11, offs=12) -- 183(line=11, offs=36)
*/
ATSINSmove_void(tmp7, atspre_print_int(tmp5)) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 159(line=11, offs=12) -- 183(line=11, offs=36)
*/
ATSINSmove_void(tmp8, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 195(line=12, offs=12) -- 214(line=12, offs=31)
*/
ATSINSmove(tmp10, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(tmp5, ATSPMVi0nt(6))) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 195(line=12, offs=12) -- 214(line=12, offs=31)
*/
ATSINSmove_void(tmp9, atspre_assert_errmsg_bool0(tmp10, ATSCSTSPmyloc("/home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 195(line=12, offs=12) -- 214(line=12, offs=31)"))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 117(line=9, offs=11) -- 118(line=9, offs=12)
*/
ATSINSmove(tmpret4, ATSPMVi0nt(0)) ;
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/ATS-parse-interpreter/test/01_factorial.dats: 117(line=9, offs=11) -- 216(line=13, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret4) ;
} /* end of [mainats_void_int] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_init(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_ATS_055_parse_055_interpreter_057_test_057_01_factorial_056_dats__dynload() ;
ATSmainats_void_int(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
