/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-6-8: 22h:43m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2
//
#include _ATS_CCOMP_PRELUDE_USER2
//
#endif /* _ATS_CCOMP_PRELUDE_USER2 */

/*
staload-prologues(beg)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer_ptr.dats: 1639(line=51, offs=1) -- 1678(line=51, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/SATS/stdio.sats: 1898(line=62, offs=1) -- 1940(line=64, offs=27)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/sys/SATS/stat.sats: 1712(line=52, offs=1) -- 1754(line=53, offs=35)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/filebas.dats: 15323(line=844, offs=1) -- 15353(line=844, offs=31)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/SATS/stdio.sats: 1898(line=62, offs=1) -- 1940(line=64, offs=27)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_t0ype(atstype_int) atslab__1 ;
} postiats_tysum_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatic()
atstkind_t0ype(atstype_int)
foo_0(atstype_boxed) ;

ATSstatic()
atstype_boxed
foo2_2(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__3(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__3__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 154(line=11, offs=5) -- 228(line=14, offs=14)
*/
/*
local: 
global: foo_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
foo_0(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 154(line=11, offs=5) -- 228(line=14, offs=14)
*/
ATSINSflab(__patsflab_foo_0):
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 177(line=12, offs=1) -- 228(line=14, offs=14)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 190(line=13, offs=3) -- 203(line=13, offs=16)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 159(line=11, offs=10) -- 160(line=11, offs=11)
*/
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 203(line=13, offs=16) -- 203(line=13, offs=16)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 196(line=13, offs=9) -- 198(line=13, offs=11)
*/
ATSINSmove(tmp1, ATSSELcon(arg0, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 200(line=13, offs=13) -- 202(line=13, offs=15)
*/
ATSINSmove(tmp2, ATSSELcon(arg0, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 207(line=13, offs=20) -- 214(line=13, offs=27)
*/
ATSINSmove(tmpret0, atspre_g0int_add_int(tmp1, tmp2)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 217(line=14, offs=3) -- 223(line=14, offs=9)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 159(line=11, offs=10) -- 160(line=11, offs=11)
*/
#if(0)
ATSifthen(ATSCKptriscons(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 223(line=14, offs=9) -- 223(line=14, offs=9)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 227(line=14, offs=13) -- 228(line=14, offs=14)
*/
ATSINSmove(tmpret0, ATSPMVi0nt(0)) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [foo_0] */

/*
/home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 235(line=17, offs=5) -- 299(line=19, offs=12)
*/
/*
local: 
global: foo2_2$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
foo2_2(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstype_boxed) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 235(line=17, offs=5) -- 299(line=19, offs=12)
*/
ATSINSflab(__patsflab_foo2_2):
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 262(line=18, offs=4) -- 267(line=18, offs=9)
*/
ATSINSmove(tmp4, ATSLIB_056_prelude__eq_g0int_int__3__1(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 259(line=18, offs=1) -- 299(line=19, offs=12)
*/
ATSif(
tmp4
) ATSthen() {
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 273(line=18, offs=15) -- 287(line=18, offs=29)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret3, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret3, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret3, postiats_tysum_0, atslab__0, ATSPMVi0nt(99)) ;
ATSINSstore_con1_ofs(tmpret3, postiats_tysum_0, atslab__1, ATSPMVi0nt(100)) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test02.dats: 293(line=19, offs=6) -- 299(line=19, offs=12)
*/

ATSINSmove_nil(tmpret3) ;

} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [foo2_2] */

#if(0)
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29359(line=813, offs=14) -- 29399(line=813, offs=54)
*/
/*
local: 
global: eq_g0int_int$3$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4529)
tmparg = S2Evar(tk(4529))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__3(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29346(line=813, offs=1) -- 29399(line=813, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29385(line=813, offs=40) -- 29397(line=813, offs=52)
*/
ATSINSmove(tmp6, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4529))>)(arg1)) ;

/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29368(line=813, offs=23) -- 29399(line=813, offs=54)
*/
ATSINSmove(tmpret5, PMVtmpltcst(g0int_eq<S2Evar(tk(4529))>)(arg0, tmp6)) ;

ATSfunbody_end()
ATSreturn(tmpret5) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__3] */
#endif // end of [TEMPLATE]

/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29359(line=813, offs=14) -- 29399(line=813, offs=54)
*/
/*
local: 
global: eq_g0int_int$3$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4529)
tmparg = S2Evar(tk(4529))
tmpsub = Some(tk(4529) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__3__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp6__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29346(line=813, offs=1) -- 29399(line=813, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29385(line=813, offs=40) -- 29397(line=813, offs=52)
*/
ATSINSmove(tmp6__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29368(line=813, offs=23) -- 29399(line=813, offs=54)
*/
ATSINSmove(tmpret5__1, atspre_g0int_eq_int(arg0, tmp6__1)) ;

ATSfunbody_end()
ATSreturn(tmpret5__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__3__1] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test02_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test02_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test02_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test02_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
