/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-12-3:  0h:14m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/basics.dats: 1534(line=44, offs=1) -- 1573(line=45, offs=32)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer_ptr.dats: 1639(line=51, offs=1) -- 1678(line=51, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/SATS/stdio.sats: 1898(line=62, offs=1) -- 1940(line=64, offs=27)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/sys/SATS/stat.sats: 1712(line=52, offs=1) -- 1754(line=53, offs=35)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/filebas.dats: 15323(line=844, offs=1) -- 15353(line=844, offs=31)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/SATS/stdio.sats: 1898(line=62, offs=1) -- 1940(line=64, offs=27)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
int exntag ;
char *exnmsg ;
atstkind_t0ype(atstype_int) atslab__0 ;
} postiats_tyexn_0 ;
typedef
ATSstruct {
int exntag ;
char *exnmsg ;
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_type(atstype_ptrk) atslab__1 ;
} postiats_tyexn_1 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
ATSdynexn_extdec(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp0) ;
ATSdynexn_extdec(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp1) ;
ATSdynexn_extdec(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp2) ;
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
/home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 151(line=8, offs=1) -- 171(line=8, offs=21)
*/
ATSdynexn_dec(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp0) ;
/*
/home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 172(line=9, offs=1) -- 195(line=9, offs=24)
*/
ATSdynexn_dec(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp1) ;
/*
/home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 196(line=10, offs=1) -- 227(line=10, offs=32)
*/
ATSdynexn_dec(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp2) ;
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatic()
atstkind_t0ype(atstype_int)
foo_0(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__3(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 233(line=12, offs=5) -- 363(line=16, offs=7)
*/
/*
local: 
global: foo_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
foo_0(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp6, atstype_exnconptr) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp10, atstype_exnconptr) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp14, atstype_exnconptr) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 233(line=12, offs=5) -- 363(line=16, offs=7)
*/
ATSINSflab(__patsflab_foo_0):
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 256(line=13, offs=4) -- 261(line=13, offs=9)
*/
ATSINSmove(tmp1, ATSLIB_056_prelude__eq_g0int_int__1__1(arg0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 253(line=13, offs=1) -- 363(line=16, offs=7)
*/
ATSif(
tmp1
) ATSthen() {
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 274(line=13, offs=22) -- 281(line=13, offs=29)
*/

ATSINSmove_exn0(tmp6, _057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp0) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 267(line=13, offs=15) -- 281(line=13, offs=29)
*/
ATSINSraise_exn(tmpret0, tmp6) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 290(line=14, offs=9) -- 295(line=14, offs=14)
*/
ATSINSmove(tmp7, ATSLIB_056_prelude__eq_g0int_int__1__2(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 287(line=14, offs=6) -- 363(line=16, offs=7)
*/
ATSif(
tmp7
) ATSthen() {
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 308(line=14, offs=27) -- 315(line=14, offs=34)
*/

ATSINSmove_exn1_beg()
ATSINSmove_exn1_new(tmp10, postiats_tyexn_0) ;
ATSINSstore_exn1_tag(tmp10, _057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp1) ;
ATSINSstore_exn1_msg(tmp10, _057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp1) ;
ATSINSstore_con1_ofs(tmp10, postiats_tyexn_0, atslab__0, arg0) ;
ATSINSmove_exn1_end()
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 301(line=14, offs=20) -- 316(line=14, offs=35)
*/
ATSINSraise_exn(tmpret0, tmp10) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 325(line=15, offs=9) -- 330(line=15, offs=14)
*/
ATSINSmove(tmp11, ATSLIB_056_prelude__eq_g0int_int__1__3(arg0, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 322(line=15, offs=6) -- 363(line=16, offs=7)
*/
ATSif(
tmp11
) ATSthen() {
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 343(line=15, offs=27) -- 356(line=15, offs=40)
*/

ATSINSmove_exn1_beg()
ATSINSmove_exn1_new(tmp14, postiats_tyexn_1) ;
ATSINSstore_exn1_tag(tmp14, _057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp2) ;
ATSINSstore_exn1_msg(tmp14, _057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp2) ;
ATSINSstore_con1_ofs(tmp14, postiats_tyexn_1, atslab__0, arg0) ;
ATSINSstore_con1_ofs(tmp14, postiats_tyexn_1, atslab__1, ATSPMVstring("a")) ;
ATSINSmove_exn1_end()
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 336(line=15, offs=20) -- 356(line=15, offs=40)
*/
ATSINSraise_exn(tmpret0, tmp14) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats: 362(line=16, offs=6) -- 363(line=16, offs=7)
*/
ATSINSmove(tmpret0, ATSPMVi0nt(3)) ;
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [foo_0] */

#if(0)
/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29885(line=851, offs=14) -- 29925(line=851, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4583)
tmparg = S2Evar(tk(4583))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29872(line=851, offs=1) -- 29925(line=851, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29911(line=851, offs=40) -- 29923(line=851, offs=52)
*/
ATSINSmove(tmp3, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4583))>)(arg1)) ;

/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29894(line=851, offs=23) -- 29925(line=851, offs=54)
*/
ATSINSmove(tmpret2, PMVtmpltcst(g0int_eq<S2Evar(tk(4583))>)(arg0, tmp3)) ;

ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1] */
#endif // end of [TEMPLATE]

/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29885(line=851, offs=14) -- 29925(line=851, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4583)
tmparg = S2Evar(tk(4583))
tmpsub = Some(tk(4583) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29872(line=851, offs=1) -- 29925(line=851, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29911(line=851, offs=40) -- 29923(line=851, offs=52)
*/
ATSINSmove(tmp3__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29894(line=851, offs=23) -- 29925(line=851, offs=54)
*/
ATSINSmove(tmpret2__1, atspre_g0int_eq_int(arg0, tmp3__1)) ;

ATSfunbody_end()
ATSreturn(tmpret2__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__1] */

/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29885(line=851, offs=14) -- 29925(line=851, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4583)
tmparg = S2Evar(tk(4583))
tmpsub = Some(tk(4583) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29872(line=851, offs=1) -- 29925(line=851, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29911(line=851, offs=40) -- 29923(line=851, offs=52)
*/
ATSINSmove(tmp3__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29894(line=851, offs=23) -- 29925(line=851, offs=54)
*/
ATSINSmove(tmpret2__2, atspre_g0int_eq_int(arg0, tmp3__2)) ;

ATSfunbody_end()
ATSreturn(tmpret2__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__2] */

/*
/home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29885(line=851, offs=14) -- 29925(line=851, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$3(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4583)
tmparg = S2Evar(tk(4583))
tmpsub = Some(tk(4583) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__3(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3__3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29872(line=851, offs=1) -- 29925(line=851, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29911(line=851, offs=40) -- 29923(line=851, offs=52)
*/
ATSINSmove(tmp3__3, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/alex/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29894(line=851, offs=23) -- 29925(line=851, offs=54)
*/
ATSINSmove(tmpret2__3, atspre_g0int_eq_int(arg0, tmp3__3)) ;

ATSfunbody_end()
ATSreturn(tmpret2__3) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__3] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
ATSdynexn_initize(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp0, "/home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats:exp0") ;
ATSdynexn_initize(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp1, "/home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats:exp1") ;
ATSdynexn_initize(_057_home_057_alex_057_workspace_057_MTVeri_057_scratch_057_CATS_055_atsccint_057_test_057_test04_056_dats__exp2, "/home/alex/workspace/MTVeri/scratch/CATS-atsccint/test/test04.dats:exp2") ;
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
