/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2015-4-3: 16h:57m
**
*/

/* ATSextcode_beg() */
// COMMENT_line

// COMMENT_line

// COMMENT_line

var fs = require('fs');
// COMMENT_line

eval(fs.readFileSync('./libatscc2js/CATS/basics_cats.js').toString());
eval(fs.readFileSync('./libatscc2js/CATS/integer_cats.js').toString());
eval(fs.readFileSync('./libatscc2js/CATS/string_cats.js').toString());
eval(fs.readFileSync('./libatscc2js/CATS/Node.js/basics_cats.js').toString());
eval(fs.readFileSync('./libatscc2js/CATS/Node.js/fprint_cats.js').toString());
// COMMENT_line

/* ATSextcode_end() */

var fact__statmp8

function
fact(arg0)
{
//
// knd = 0
  var tmpret0
  var tmp1
  var tmp2
  var tmp3
//
  // __patsflab_fact
  tmp1 = ats2jspre_gt_int0_int0(arg0, 0);
  if(tmp1) {
    tmp3 = ats2jspre_sub_int0_int0(arg0, 1);
    tmp2 = fact(tmp3);
    tmpret0 = ats2jspre_mul_int0_int0(arg0, tmp2);
  } else {
    tmpret0 = 1;
  } // endif
  return tmpret0;
} // end-of-function

// dynloadflag_init
var _057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_fact_056_dats__dynloadflag = 0;

function
_057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_fact_056_dats__dynload()
{
//
// knd = 0
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_fact_056_dats__dynloadflag(28))
  if(ATSCKiseqz(_057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_fact_056_dats__dynloadflag)) {
    _057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_fact_056_dats__dynloadflag = 1 ; // flag is set
    ats2jspre_print_string("fact(");
    ats2jspre_print_int(10);
    ats2jspre_print_string(") = ");
    fact__statmp8 = fact(10);
    ats2jspre_print_int(fact__statmp8);
    ats2jspre_print_newline();
  } // endif
  return/*_void*/;
} // end-of-function


function
fact_dynload()
{
//
// knd = 0
//
  _057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_fact_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
fact_dynload()
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
