/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2015-4-3: 16h:29m
**
*/

/* ATSextcode_beg() */
// COMMENT_line

// COMMENT_line

// COMMENT_line

var fs = require('fs');
eval(fs.readFileSync('./libatscc2js/CATS/basics_cats.js').toString());
eval(fs.readFileSync('./libatscc2js/CATS/Node.js/basics_cats.js').toString());
eval(fs.readFileSync('./libatscc2js/CATS/Node.js/fprint_cats.js').toString());
eval(fs.readFileSync('./libatscc2js/CATS/Node.js/process_cats.js').toString());
/* ATSextcode_end() */
// dynloadflag_init
var _057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_hello_056_dats__dynloadflag = 0;

function
_057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_hello_056_dats__dynload()
{
//
// knd = 0
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_hello_056_dats__dynloadflag(14))
  if(ATSCKiseqz(_057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_hello_056_dats__dynloadflag)) {
    _057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_hello_056_dats__dynloadflag = 1 ; // flag is set
    ats2nodejs_fprint_string(ats2nodejs_process_stdout, "Hello world!");
    ats2nodejs_fprint_newline(ats2nodejs_process_stdout);
  } // endif
  return/*_void*/;
} // end-of-function


function
hello_dynload()
{
//
// knd = 0
//
  _057_home_057_grad2_057_aren_057_programs_057_ats2_github_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_ATS_055_parse_055_emit_057_JavaScript_057_MYTEST_057_hello_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
hello_dynload()
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
